### ISSUE TITLE
Selenium Webdriver - actions().mouseMove() throwing error

### ISSUE THREAD

**Issue by guptarajatkn** [vladikoff/node-geckodriver#14]
UnknownCommandError: POST /session/f4d187e1-c7f7-4c2f-b56d-5284af8fac88/moveto did not match a known command
         at WebDriverError (C:\UI_Automation_New\node_modules\selenium-webdriver\lib\error.js:27:5)
         at UnknownCommandError (C:\UI_Automation_New\node_modules\selenium-webdriver\lib\error.js:296:5)
         at Object.throwDecodedError (C:\UI_Automation_New\node_modules\selenium-webdriver\lib\error.js:477:11)
         at parseHttpResponse (C:\UI_Automation_New\node_modules\selenium-webdriver\lib\http.js:499:15)
         at doSend.then.response (C:\UI_Automation_New\node_modules\selenium-webdriver\lib\http.js:440:13)
         at process._tickCallback (internal/process/next_tick.js:103:7)
     From: Task: mouseMove
         at thenableWebDriverProxy.schedule (C:\UI_Automation_New\node_modules\selenium-webdriver\lib\webdriver.js:816:17)
         at actions.map.action (C:\UI_Automation_New\node_modules\selenium-webdriver\lib\actions.js:124:23)
         at Array.map (native)
         at C:\UI_Automation_New\node_modules\selenium-webdriver\lib\actions.js:123:29
         at TaskQueue.execute_ (C:\UI_Automation_New\node_modules\selenium-webdriver\lib\promise.js:2970:14)
         at TaskQueue.executeNext_ (C:\UI_Automation_New\node_modules\selenium-webdriver\lib\promise.js:2953:27)
         at asyncRun (C:\UI_Automation_New\node_modules\selenium-webdriver\lib\promise.js:2860:25)
         at C:\UI_Automation_New\node_modules\selenium-webdriver\lib\promise.js:676:7
         at process._tickCallback (internal/process/next_tick.js:103:7)
     From: Task: ActionSequence.perform
         at ActionSequence.perform (C:\UI_Automation_New\node_modules\selenium-webdriver\lib\actions.js:122:33)
         at C:\UI_Automation_New\page-objects\addPerson_page.js:56:78
         at ManagedPromise.invokeCallback_ (C:\UI_Automation_New\node_modules\selenium-webdriver\lib\promise.js:1366:14)
         at TaskQueue.execute_ (C:\UI_Automation_New\node_modules\selenium-webdriver\lib\promise.js:2970:14)
         at TaskQueue.executeNext_ (C:\UI_Automation_New\node_modules\selenium-webdriver\lib\promise.js:2953:27)
         at asyncRun (C:\UI_Automation_New\node_modules\selenium-webdriver\lib\promise.js:2813:27)
         at C:\UI_Automation_New\node_modules\selenium-webdriver\lib\promise.js:676:7
         at process._tickCallback (internal/process/next_tick.js:103:7)

**Comment by vladikoff** [comment]
@guptarajatkn please file a detailed issue at https://github.com/SeleniumHQ/selenium/issues
