### ISSUE TITLE
npm install failure where geckodriver is a dependency

### ISSUE THREAD

**Issue by alarimer** [vladikoff/node-geckodriver#39]
Added gulp-galenframework 2.3.6 to packages.json in Visual Studio 2017 which triggered npm.

## Result

```
PATH=.\node_modules\.bin;C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Web\External;%PATH%;C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\Git\cmd;C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\Git\mingw32\bin
"C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Web\External\npm.CMD" install
> geckodriver@1.10.0 postinstall C:\Users\USER\source\repos\Appliction\Application.Tests\node_modules\geckodriver
> node index.js
C:\Users\USER\source\repos\Application\Application.Tests\node_modules\tar\lib\pack.js:32
const EOF = Buffer.alloc(1024)
                   ^
TypeError: Buffer.alloc is not a function
    at Object.<anonymous> (C:\Users\USER\source\repos\Application\Application.Tests\node_modules\tar\lib\pack.js:32:20)
    at Module._compile (module.js:397:26)
    at Object.Module._extensions..js (module.js:404:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\USER\source\repos\Application\Application.Tests\node_modules\tar\lib\create.js:6:14)
    at Module._compile (module.js:397:26)
    at Object.Module._extensions..js (module.js:404:10)
npm WARN EPACKAGEJSON acornwebsite.tests@1.0.0 No description
npm WARN EPACKAGEJSON acornwebsite.tests@1.0.0 No repository field.
npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Enterprise\\Web\\External\\Node.exe" "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Enterprise\\Web\\External\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v5.4.1
npm ERR! npm  v3.3.4
npm ERR! code ELIFECYCLE
npm ERR! geckodriver@1.10.0 postinstall: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the geckodriver@1.10.0 postinstall script 'node index.js'.
npm ERR! This is most likely a problem with the geckodriver package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node index.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls geckodriver
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\USER\source\repos\Application\Application.Tests\npm-debug.log
```

npm-debug.log available upon request.

## Environment

Platform: Windows 10
NodeJS version: 8.9.3
npm version: 5.5.1
Gulp version: 3.9.1
Java version: 8 Update 151

**Comment by alarimer** [comment]
Not sure what happened, but running some _npm_ commands from the command line seemed to resolve the issue.

**Comment by alarimer** [comment]
Not sure what happened, but running some _npm_ commands from the command line seemed to resolve the issue.
