### ISSUE TITLE
npm install --save-dev geckodriver failing with RequestError: connect ETIMEDOUT 

### ISSUE THREAD

**Issue by vasu512** [vladikoff/node-geckodriver#71]
npm install --save-dev geckodriver is failing with below error

```
PS D:\cloud-lab\test> npm install --save-dev geckodriver

> geckodriver@1.19.1 postinstall D:\cloud-lab\test\node_modules\geckodriver
> node index.js

Downloading geckodriver...
events.js:174
      throw er; // Unhandled 'error' event
      ^
RequestError: connect ETIMEDOUT 13.250.177.223:443
    at ClientRequest.<anonymous> (D:\cloud-lab\test\node_modules\got\index.js:69:21)
    at Object.onceWrapper (events.js:286:20)
    at ClientRequest.emit (events.js:198:13)
    at TLSSocket.socketErrorListener (_http_client.js:392:9)
    at TLSSocket.emit (events.js:198:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at EventEmitter.emit (events.js:198:13)
    at ClientRequest.<anonymous> (D:\cloud-lab\test\node_modules\got\index.js:69:7)
    at Object.onceWrapper (events.js:286:20)
    [... lines matching original stack trace ...]
    at process._tickCallback (internal/process/next_tick.js:63:19)
npm WARN enoent ENOENT: no such file or directory, open 'D:\cloud-lab\test\package.json'
npm WARN test No description
npm WARN test No repository field.
npm WARN test No README data
npm WARN test No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! geckodriver@1.19.1 postinstall: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the geckodriver@1.19.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\srmuppal\AppData\Roaming\npm-cache\_logs\2019-11-08T13_36_11_494Z-debug.log
```

**Comment by vladikoff** [comment]
are you behind a proxy or something?

**Comment by vasu512** [comment]
Yes, I am behind the proxy

**Comment by vladikoff** [comment]
you might be able to use one of the configuration options , to either use a proxy url or a custom download path url
https://github.com/vladikoff/node-geckodriver#setting-a-proxy-url
